-- WhatsOrder tenant/auth/order security hardening
-- Run after schema.sql and super_admin_migration.sql.

create table if not exists public.order_submission_attempts (
  id bigint generated by default as identity primary key,
  restaurant_id uuid not null references public.restaurants(id) on delete cascade,
  client_fingerprint text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_order_submission_attempts_lookup
on public.order_submission_attempts(restaurant_id, client_fingerprint, created_at desc);

alter table public.order_submission_attempts enable row level security;

-- This table is intentionally service-role only. No anon/authenticated policies are created.

create or replace function public.is_restaurant_member(
  target_restaurant_id uuid,
  allowed_roles text[] default null
)
returns boolean
language sql
stable
security definer
set search_path = public
as $membership$
  select exists (
    select 1
    from public.restaurant_users
    where restaurant_users.restaurant_id = target_restaurant_id
      and restaurant_users.user_id = auth.uid()
      and restaurant_users.accepted_at is not null
      and (
        allowed_roles is null
        or restaurant_users.role = any(allowed_roles)
      )
  );
$membership$;

create or replace function public.check_order_submission_rate_limit(
  target_restaurant_id uuid,
  target_client_fingerprint text,
  attempt_limit integer default 8,
  window_size_seconds integer default 600
)
returns boolean
language plpgsql
security definer
set search_path = public
as $rate_limit$
declare
  recent_attempts integer;
begin
  if attempt_limit < 1 or window_size_seconds < 1 then
    return false;
  end if;

  delete from public.order_submission_attempts
  where created_at < now() - interval '1 day';

  select count(*)
  into recent_attempts
  from public.order_submission_attempts
  where restaurant_id = target_restaurant_id
    and client_fingerprint = target_client_fingerprint
    and created_at >= now() - make_interval(secs => window_size_seconds);

  if recent_attempts >= attempt_limit then
    return false;
  end if;

  insert into public.order_submission_attempts (restaurant_id, client_fingerprint)
  values (target_restaurant_id, target_client_fingerprint);

  return true;
end;
$rate_limit$;

revoke all on function public.check_order_submission_rate_limit(uuid, text, integer, integer)
from public, anon, authenticated;
grant execute on function public.check_order_submission_rate_limit(uuid, text, integer, integer)
to service_role;

create or replace function public.create_order_with_customer(
  target_restaurant_id uuid,
  order_customer_name text,
  order_customer_phone text,
  order_delivery_area text,
  order_delivery_address text,
  order_delivery_latitude numeric,
  order_delivery_longitude numeric,
  order_delivery_google_maps_url text,
  order_delivery_place_id text,
  order_delivery_address_text text,
  order_delivery_landmark text,
  order_notes text,
  order_payment_method text,
  order_items jsonb,
  order_subtotal numeric,
  order_delivery_fee numeric,
  order_total numeric,
  order_whatsapp_message text,
  order_consent_processing boolean,
  order_consent_marketing boolean,
  order_consent_timestamp timestamptz
)
returns uuid
language plpgsql
security definer
set search_path = public
as $create_order$
declare
  new_order_id uuid;
begin
  if not order_consent_processing then
    raise exception 'Order-processing consent is required';
  end if;

  if jsonb_typeof(order_items) <> 'array' or jsonb_array_length(order_items) = 0 then
    raise exception 'Order items are required';
  end if;

  if order_subtotal < 0 or order_delivery_fee < 0 or order_total < 0 then
    raise exception 'Order totals cannot be negative';
  end if;

  if not exists (
    select 1
    from public.restaurants
    where id = target_restaurant_id
      and is_active = true
      and status in ('live', 'trial', 'paid')
  ) then
    raise exception 'Restaurant is not accepting orders';
  end if;

  insert into public.orders (
    restaurant_id,
    customer_name,
    customer_phone,
    delivery_area,
    delivery_address,
    delivery_latitude,
    delivery_longitude,
    delivery_google_maps_url,
    delivery_place_id,
    delivery_address_text,
    delivery_landmark,
    notes,
    payment_method,
    items,
    subtotal,
    delivery_fee,
    total,
    points_earned,
    points_redeemed,
    loyalty_discount,
    status,
    whatsapp_message,
    consent_order_processing,
    consent_marketing,
    consent_timestamp
  )
  values (
    target_restaurant_id,
    order_customer_name,
    order_customer_phone,
    order_delivery_area,
    order_delivery_address,
    order_delivery_latitude,
    order_delivery_longitude,
    order_delivery_google_maps_url,
    order_delivery_place_id,
    order_delivery_address_text,
    order_delivery_landmark,
    order_notes,
    order_payment_method::public.payment_method,
    order_items,
    order_subtotal,
    order_delivery_fee,
    order_total,
    0,
    0,
    0,
    'New',
    order_whatsapp_message,
    order_consent_processing,
    order_consent_marketing,
    order_consent_timestamp
  )
  returning id into new_order_id;

  insert into public.customers (
    restaurant_id,
    name,
    phone,
    delivery_area,
    delivery_address,
    default_latitude,
    default_longitude,
    default_google_maps_url,
    default_address_text,
    default_landmark,
    total_orders,
    total_spend,
    last_order_at,
    marketing_opt_in,
    consent_order_processing,
    consent_marketing,
    consent_timestamp,
    loyalty_points_balance,
    lifetime_points_earned,
    updated_at
  )
  values (
    target_restaurant_id,
    order_customer_name,
    order_customer_phone,
    order_delivery_area,
    order_delivery_address,
    order_delivery_latitude,
    order_delivery_longitude,
    order_delivery_google_maps_url,
    order_delivery_address_text,
    order_delivery_landmark,
    1,
    order_total,
    order_consent_timestamp,
    order_consent_marketing,
    order_consent_processing,
    order_consent_marketing,
    order_consent_timestamp,
    0,
    0,
    order_consent_timestamp
  )
  on conflict (restaurant_id, phone) do update set
    name = excluded.name,
    delivery_area = excluded.delivery_area,
    delivery_address = excluded.delivery_address,
    default_latitude = excluded.default_latitude,
    default_longitude = excluded.default_longitude,
    default_google_maps_url = excluded.default_google_maps_url,
    default_address_text = excluded.default_address_text,
    default_landmark = excluded.default_landmark,
    total_orders = customers.total_orders + 1,
    total_spend = customers.total_spend + excluded.total_spend,
    last_order_at = excluded.last_order_at,
    marketing_opt_in = customers.marketing_opt_in or excluded.marketing_opt_in,
    consent_order_processing = excluded.consent_order_processing,
    consent_marketing = customers.consent_marketing or excluded.consent_marketing,
    consent_timestamp = excluded.consent_timestamp,
    updated_at = excluded.updated_at;

  return new_order_id;
end;
$create_order$;

revoke all on function public.create_order_with_customer(
  uuid, text, text, text, text, numeric, numeric, text, text, text, text, text,
  text, jsonb, numeric, numeric, numeric, text, boolean, boolean, timestamptz
) from public, anon, authenticated;
grant execute on function public.create_order_with_customer(
  uuid, text, text, text, text, numeric, numeric, text, text, text, text, text,
  text, jsonb, numeric, numeric, numeric, text, boolean, boolean, timestamptz
) to service_role;

create index if not exists idx_restaurant_users_active_user
on public.restaurant_users(user_id, accepted_at)
where user_id is not null;

-- Preserve pre-invitation accounts created before accepted_at existed.
update public.restaurant_users
set accepted_at = coalesce(created_at, now())
where user_id is not null
  and accepted_at is null
  and invited_at is null;

drop policy if exists "Restaurant users can manage own loyalty transactions"
on public.loyalty_transactions;
create policy "Restaurant users can manage own loyalty transactions"
on public.loyalty_transactions for all
using (
  is_restaurant_member(
    loyalty_transactions.restaurant_id,
    array['restaurant_admin', 'owner', 'manager', 'staff']
  )
)
with check (
  is_restaurant_member(
    loyalty_transactions.restaurant_id,
    array['restaurant_admin', 'owner', 'manager', 'staff']
  )
);

notify pgrst, 'reload schema';
